import "../styles/main.css";
import { inter, lora, myFont } from "../styles/fonts";
import Alert from "./components/Alert";
import Navbar from "./components/Navbar";
import InteractiveCircle from "./components/InteractiveCircle";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Kisakye Moses | Uncle Moses",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`font-bold ${myFont.className}`}>
        <ToastContainer position='top-center' />
        {/* <InteractiveCircle /> */}
        <Navbar />
        <Alert />
        {children}
      </body>
    </html>
  );
}
